//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTFW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int userId { get; set; }
        public string accountName { get; set; }
        public string password { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
